apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-k8s-streamlit
  namespace: your-namespace
  labels:
    app: kserve-k8s-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kserve-k8s-streamlit
  template:
    metadata:
      labels:
        app: kserve-k8s-streamlit
    spec:
      serviceAccountName: default-editor
      imagePullSecrets:
      - name: gar-json-key
      nodeSelector:
        cloud.google.com/gke-nodepool: default-node-pool-new
      containers:
      - name: kserve-k8s-streamlit
        image: us-central1-docker.pkg.dev/gcp-prj-id-123/mlflow-gcp/kserve-k8s-streamlit-app
        envFrom:
          - configMapRef:
              name: kserve-k8s-streamlit-config
        resources:
          limits:
            memory: 200Mi
            cpu: 50m
          requests:
            memory: 100Mi
            cpu: 50m
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: kube-api-access
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      volumes:
      - name: kube-api-access
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
          - configMap:
              name: kube-root-ca.crt
              items:
              - key: ca.crt
                path: ca.crt
          - downwardAPI:
              items:
              - path: namespace
                fieldRef:
                  fieldPath: metadata.namespace
