apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
  namespace: your-namespace
spec:
  selector:
    app: kserve-k8s-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
